# Generated by Django 3.2.9 on 2022-06-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20220608_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
