# Generated by Django 3.2.9 on 2022-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_billfold_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_Billfold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, null=True)),
                ('billfold', models.CharField(max_length=30, null=True)),
                ('inflow', models.CharField(max_length=20, null=True)),
                ('outflow', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='billfold',
            name='inflow',
        ),
        migrations.RemoveField(
            model_name='billfold',
            name='outflow',
        ),
    ]
