# Generated by Django 3.2.9 on 2022-06-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20220609_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track_Billfold',
            new_name='Track',
        ),
    ]
