# Generated by Django 3.2.9 on 2022-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_track_billfold_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='date',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='track',
            name='inflow',
        ),
        migrations.RemoveField(
            model_name='track',
            name='outflow',
        ),
        migrations.AddField(
            model_name='track',
            name='balance',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
