# Generated by Django 3.2.9 on 2022-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20220609_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='inflow',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='outflow',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
