# Generated by Django 3.2.9 on 2022-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20220609_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
