# Generated by Django 3.2.9 on 2022-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_transaction_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
